config/routes.rb
Rails.application.routes.draw do
  # get 'restaurants/index'
  # get 'restaurants/new'
  # get 'restaurants/create'
  # get 'restaurants/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # verb "url", to: "controller#action"

  # A visitor can see the list of all restaurants
  # get 'restaurants', to: "restaurants#index"

  # # A visitor can add a new restaurant, and be redirected to the show view of that new restaurant.
  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"

  # # A visitor can see the details of a restaurant, with all the reviews related to the restaurant.
  # get "restaurants/:id", to: "restaurants#show"

  # # A visitor can add a new review to a restaurant
  # get "restaurants/38/reviews/new", to: "reviews#new"
  # post "restaurants/38/reviews", to: "reviews#create"
  
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"] 

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true

  # YOU CAN USE EITHER
  # validates :category, presence: true, inclusion: {in: %w(chinese italian japanese french belgian)}  
  validates :category, presence: true, inclusion: {in: CATEGORIES}  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    @review.restaurant = @restaurant
  end

  def create
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    
    @review = Review.new(review_params)

    # Give the review the correct restaurant id. We've given it a rating and content, now it just needs an id.
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    # You only need to put in here information that comes from your form
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvpReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>

        <%# YOU CAN USE EITHER OF THESE %>
        <%# <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
        <%= f.input :category, collection: Restaurant::CATEGORIES %>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
  <h1>Restaurants</h1>
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <ul class="list-group">
      <% @restaurants.each do |restaurant| %>
      <li class="list-group-item">
        <p><%= link_to restaurant.name, restaurant_path(restaurant) %><%= restaurant.phone_number %></p>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.category %></p>
      </li>
      <% end %>
    <%= link_to "Add a new Restaurant", new_restaurant_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new restaurant</h1>

      <%= render 'form', restaurant: @restaurant %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @restaurant.name %></h1>
      <table class="table table-bordered">
          <tr>
            <th scope="row">Address</th>
            <td><%= @restaurant.address %></td>
          </tr>
          <tr>
            <th scope="row">Phone Number</th>
            <td><%= @restaurant.phone_number %></td>
          </tr>
          <tr>
            <th scope="row">Category</th>
            <td><%= @restaurant.category %></td>
          </tr>
      </table>
      
      <%# @restaurant.reviews is an array %>
      <%# we can call .reviews in @restaurant because in our restaurant model it has_many reviews %>
       <div class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item">
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            <p><%= review.content %></p>
        <%= link_to "delete", review_path(review), method: :delete %>
          </li>
        <% end %>
      </div>


      <%# You can't just use @review because in the routes both reviews paths require @restaurant id as well. %>
      <h1>Reviews</h1>
      <%= form_for [@restaurant, @review] do |f| %>
        <%= f.label :rating %>
        <%= f.number_field :rating, collection: 0..5 %>
        <%= f.label :content %>
        <%= f.text_field :content %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

      <%= link_to "Back to all restaurants", restaurants_path, class: "btn btn-primary"%>

    </div>
  </div>
</div>